name: spotify_clone
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  google_fonts: ^3.0.1
  easy_localization: ^3.0.1
  get: ^4.6.5
  audio_video_progress_bar: ^0.11.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/
  - assets/images/
  - assets/images/icons/
  - assets/images/icons/2.0x/
  - assets/images/icons/3.0x/
  - assets/translations/

